# Generated by Django 5.2.1 on 2025-05-18 03:32

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.avatar_upload_path),
        ),
    ]
