# Generated by Django 5.2.1 on 2025-05-18 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tmdb', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Favoritos', max_length=255)),
                ('padrao', models.BooleanField(default=False)),
                ('filmes', models.ManyToManyField(blank=True, related_name='listas_onde_esta', to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_de_filmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Filmes do Usuário',
                'verbose_name_plural': 'Listas de Filmes dos Usuários',
                'unique_together': {('usuario', 'nome')},
            },
        ),
    ]
